== Day 20

This solution is written in python.

The following libraries are used to implement the solution:

* Typer (https://typer.tiangolo.com/) to generate a nice command line interface
* pathlib (https://docs.python.org/3/library/pathlib.html)
* deepcopy from copy (https://docs.python.org/3/library/copy.html)
* combinations form itertools (https://docs.python.org/3/library/itertools.html#itertools.combinations)
* defaultdict and deque from collections (https://docs.python.org/3/library/collections.html#collections.defaultdict)

=== Main idea

Solution for today is quite slow but clean.

The idea for part 1 is to sort all bricks by there z-coordinate. For dropping
the bricks I created a dict containing the current height at a (x,y) coordinat. 
I then looped through the sorted bricks and calculated the new z-coordinate 
by cechking all coordinated of a brick. Initially, I forgot to handle "standing"
bricks (i.e. different z-coordinate between start and end).
Finally, I calculated a support dict that stored for each brick a list of 
supporting bricks.

Part 2 was rather simple with my data structure form part 1. Just do a BFS for
each ID and count the number of bricks that woud fall it the ID is removed 

=== What did I learn

Run using:
`$ python day_21.py --help`
